import type { Document } from './DocumentTypes';

export const documentsData: Document[] = [
  {
    id: 'DOC001',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT001',
    patientName: 'Nguyễn Thị Anh',
    doctorId: 'DR001',
    doctorName: 'Bs. Nguyễn Thị Hương',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-001.pdf',
    status: 'active',
    isFavorite: true
  },
  {
    id: 'DOC002',
    title: 'Đơn thuốc của Bs. Inglais',
    type: 'prescription',
    patientId: 'PT001',
    patientName: 'Nguyễn Thị Anh',
    doctorId: 'DR002',
    doctorName: 'Bs. David Inglais',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/prescription-thumb.png',
    fileUrl: '/documents/prescription-001.pdf',
    status: 'active',
    isFavorite: false
  },
  {
    id: 'DOC003',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT002',
    patientName: 'Trần Văn Bình',
    doctorId: 'DR001',
    doctorName: 'Bs. Nguyễn Thị Hương',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-002.pdf',
    status: 'active',
    isFavorite: true
  },
  {
    id: 'DOC004',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT003',
    patientName: 'Lê Thị Cúc',
    doctorId: 'DR001',
    doctorName: 'Bs. Nguyễn Thị Hương',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-003.pdf',
    status: 'active',
    isFavorite: true
  },
  {
    id: 'DOC005',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT004',
    patientName: 'Phạm Văn Dũng',
    doctorId: 'DR003',
    doctorName: 'Bs. Trần Văn Minh',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-004.pdf',
    status: 'active',
    isFavorite: true
  },
  {
    id: 'DOC006',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT005',
    patientName: 'Hoàng Thị Em',
    doctorId: 'DR001',
    doctorName: 'Bs. Nguyễn Thị Hương',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-005.pdf',
    status: 'active',
    isFavorite: true
  },
  {
    id: 'DOC007',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT006',
    patientName: 'Ngô Văn Pháp',
    doctorId: 'DR003',
    doctorName: 'Bs. Trần Văn Minh',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-006.pdf',
    status: 'active',
    isFavorite: false
  },
  {
    id: 'DOC008',
    title: 'Báo cáo xét nghiệm máu',
    type: 'report',
    patientId: 'PT007',
    patientName: 'Đỗ Thị Giang',
    doctorId: 'DR004',
    doctorName: 'Bs. Lê Thị An',
    createdAt: '14/05/2023 13:25',
    updatedAt: '14/05/2023 13:25',
    thumbnailUrl: '/images/documents/blood-report-thumb.png',
    fileUrl: '/documents/blood-report-007.pdf',
    status: 'active',
    isFavorite: false
  }
]; 