import type { Patient } from './PatientTypes';

export const patientsData: Patient[] = [
  {
    id: 'PT001',
    fullName: 'Nguyễn Văn A',
    phone: '0912345678',
    email: 'nguyenvana@gmail.com',
    gender: 'Male',
    birthdate: '15/05/1985',
    address: 'Số 123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '01/01/2023',
    medicalRecord: 'MR001',
    consultant: 'Bác sĩ Trần Văn X',
    reason: 'Khám sức khỏe định kỳ'
  },
  {
    id: 'PT002',
    fullName: 'Trần Thị B',
    phone: '0923456789',
    email: 'tranthib@gmail.com',
    gender: 'Female',
    birthdate: '20/07/1990',
    address: 'Số 456 Đường Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '15/01/2023',
    medicalRecord: 'MR002',
    consultant: 'Bác sĩ Nguyễn Thị Y',
    reason: 'Theo dõi thai kỳ'
  },
  {
    id: 'PT003',
    fullName: 'Lê Văn C',
    phone: '0934567890',
    email: 'levanc@gmail.com',
    gender: 'Male',
    birthdate: '10/03/1982',
    address: 'Số 789 Đường Trần Hưng Đạo, Quận 5, TP. Hồ Chí Minh',
    status: 'inactive',
    registeredDate: '05/02/2023',
    medicalRecord: 'MR003',
    consultant: 'Bác sĩ Phạm Văn Z',
    reason: 'Đau đầu, sốt'
  },
  {
    id: 'PT004',
    fullName: 'Phạm Thị D',
    phone: '0945678901',
    email: 'phamthid@gmail.com',
    gender: 'Female',
    birthdate: '25/12/1995',
    address: 'Số 101 Đường Cách Mạng Tháng 8, Quận 3, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '20/02/2023',
    medicalRecord: 'MR004',
    consultant: 'Bác sĩ Trần Văn X',
    reason: 'Tư vấn dinh dưỡng'
  },
  {
    id: 'PT005',
    fullName: 'Hoàng Văn E',
    phone: '0956789012',
    email: 'hoangvane@gmail.com',
    gender: 'Male',
    birthdate: '30/08/1988',
    address: 'Số 202 Đường Nguyễn Thị Minh Khai, Quận 3, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '10/03/2023',
    medicalRecord: 'MR005',
    consultant: 'Bác sĩ Nguyễn Thị Y',
    reason: 'Khám sức khỏe định kỳ'
  },
  {
    id: 'PT006',
    fullName: 'Ngô Thị F',
    phone: '0967890123',
    email: 'ngothif@gmail.com',
    gender: 'Female',
    birthdate: '05/10/1992',
    address: 'Số 303 Đường Võ Văn Tần, Quận 3, TP. Hồ Chí Minh',
    status: 'inactive',
    registeredDate: '25/03/2023',
    medicalRecord: 'MR006',
    consultant: 'Bác sĩ Phạm Văn Z',
    reason: 'Tư vấn kế hoạch hóa gia đình'
  },
  {
    id: 'PT007',
    fullName: 'Đỗ Văn G',
    phone: '0978901234',
    email: 'dovang@gmail.com',
    gender: 'Male',
    birthdate: '12/04/1980',
    address: 'Số 404 Đường Điện Biên Phủ, Quận Bình Thạnh, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '05/04/2023',
    medicalRecord: 'MR007',
    consultant: 'Bác sĩ Trần Văn X',
    reason: 'Đau lưng mãn tính'
  },
  {
    id: 'PT008',
    fullName: 'Vũ Thị H',
    phone: '0989012345',
    email: 'vuthih@gmail.com',
    gender: 'Female',
    birthdate: '18/06/1993',
    address: 'Số 505 Đường Phan Xích Long, Quận Phú Nhuận, TP. Hồ Chí Minh',
    status: 'active',
    registeredDate: '20/04/2023',
    medicalRecord: 'MR008',
    consultant: 'Bác sĩ Nguyễn Thị Y',
    reason: 'Siêu âm thai'
  }
]; 